### ISSUE TITLE
Сan't find UTF-8 charset

### ISSUE THREAD

**Issue by adelnizamutdinov** [airbnb/okreplay#56]
https://github.com/airbnb/okreplay/blob/bb43d398db8b2759c588079ced680592752edf7f/okreplay-core/src/main/java/okreplay/AbstractMessage.java#L46-L52

```
Caused by: java.lang.RuntimeException: java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]
  at okreplay.AbstractMessage.bodyAsText(AbstractMessage.java:50)
  at okreplay.RecordedMessage.maybeBodyAsString(RecordedMessage.java:49)
  at okreplay.RecordedRequest.toYaml(RecordedRequest.java:55)
  at okreplay.RecordedRequest.toYaml(RecordedRequest.java:18)
  at okreplay.RecordedInteraction.toYaml(RecordedInteraction.java:30)
  at okreplay.MemoryTape.record(MemoryTape.java:139)
  at okreplay.YamlTape.record(YamlTape.java:15)
  at okreplay.OkReplayInterceptor.intercept(OkReplayInterceptor.java:54)
```

```
Caused by: java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]
    at java.nio.charset.Charset.forNameUEE(Charset.java:322)
    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:63)
    at okreplay.AbstractMessage.bodyAsText(AbstractMessage.java:48)
```

Ok, so apparently this is what happens: `Charset.forName("java.nio.charset.CharsetICU[UTF-8]")`, which is definitely not what you want.
It happens because of the `toString` here:

https://github.com/airbnb/okreplay/blob/bb43d398db8b2759c588079ced680592752edf7f/okreplay-core/src/main/java/okreplay/AbstractMessage.java#L33

**Comment by adelnizamutdinov** [comment]
basically, what happens is:

```kotlin
Charset.forName(Charset.defaultCharset().toString())
```

how do you guys use this?

**Comment by felipecsl** [comment]
I don't know why I closed this, can't remember doing that either, but it does sounds like an actual bug.

**Comment by slavasav** [comment]
Same issue with API 23 simulator. Works on API 25 though.

**Comment by nuxusr** [comment]
@felipecsl - I think you were ok with closing it. It was resolved for me in that commit bdc4e30 by returning the Charset and not doing the .toString().  

When is the next release? I don't see it fixed in 1.4.0-SNAPSHOT

**Comment by felipecsl** [comment]
`1.4.0-SNAPSHOT` should be [live](https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/okreplay/) including the changes in https://github.com/airbnb/okreplay/commit/bdc4e30d770604201168f6772042528d553b97b9 now.
It's also been updated for support to the new Android Gradle Plugin v3.0 rc1.
Please let me know if you see any issues!

**Comment by islamfarid** [comment]
hello, i tried to put 1.4.0-SNAPSHOT instead of 1.3.0 but gradle told me couldn't find 1.4.0-SNAPSHOT so should i take the .aar from okreplay open source code or you have the complete dependencies of okreplay 1.4.0-SNAPSHOT ... please help me as i found the same exception and i want to use this library

**Comment by felipecsl** [comment]
@islamfarid you can find the SNAPSHOT [here](https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/okreplay/espresso/1.4.0-SNAPSHOT/)
in order to use it, you have to add `maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }` to your gradle repositories setup
